name: Mutation Analysis

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: 'maven'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn clean package -DskipTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Rename jar
        run: cp checker/target/checker-*-jar-with-dependencies.jar checker.jar
      - name: Checkout Py2EO
        uses: actions/checkout@v3
        with:
          repository: 'polystat/py2eo'
      - name: Run mutation analysis
        run: java -jar checker.jar transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests www
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www
          clean: false