name: Mutation Analysis

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: 'maven'
      - name: Run tests
        run: mvn clean test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Rename jar
        run: cp target/checker-*-jar-with-dependencies.jar checker.jar
      - name: Checkout Py2EO
        uses: actions/checkout@v3
        with:
          repository: 'polystat/py2eo'
      - run: cd ..
      - run: tree
      - name: Run mutation analysis
        run: cd .. & java -jar checker.jar py2eo/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests www
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www
          clean: false